version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: aws-sdk-sns
    versions:
    - 1.37.0
    - 1.38.0
    - 1.39.0
  - dependency-name: sucker_punch
    versions:
    - 2.1.2
    - 3.0.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: webdrivers
    versions:
    - 4.5.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: delayed_job_active_record
    versions:
    - 4.1.5
